plugins {
    id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

jar {
    archiveBaseName = 'pmd-additional-rules'
    from sourceSets.main.output
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.sourceforge.pmd:pmd-java:7.19.0'
}