spring:
  application:
    name: BE
  config:
    import: optional:file:env.yaml

  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: ${SHOW_SQL}

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: MySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLongForHS256Algorithm
  expiration: 86400000

springdoc:
  api-docs:
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html