spring:
  application:
    name: BE
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:tododb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: MySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLongForHS256Algorithm
  expiration: 86400000

springdoc:
  api-docs:
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html